import type { GameConfig } from "../../config/types";

export const dustHarborConfig: GameConfig = {
  game: {
    id: "dust-harbor",
    title: "Dust Harbor",
    version: 1,
    theme: {
      background: "#111827",
      panel: "#1f2937",
      accent: "#38bdf8",
    },
  },
  resources: [
    {
      id: "charge",
      name: "Charge",
      icon: "bolt",
      startingValue: 18,
      cap: 28,
      passiveRate: { type: "constant", value: 1.4 },
      resetOnRun: true,
    },
    { id: "parts", name: "Parts", icon: "gear", startingValue: 0 },
    { id: "supplies", name: "Supplies", icon: "crate", startingValue: 5, cap: 14, resetOnRun: true },
    { id: "charts", name: "Charts", icon: "signal", startingValue: 0 },
  ],
  units: [
    {
      id: "harbor-crew",
      name: "Harbor Crew",
      role: "fighter",
      cost: { charge: 6, supplies: 1 },
      health: { type: "constant", value: 30 },
      damage: { type: "constant", value: 6 },
      attackRate: { type: "constant", value: 1 },
      speed: { type: "constant", value: 44 },
      targetPriority: "nearest",
      unlock: { type: "always" },
    },
    {
      id: "skiff-drone",
      name: "Skiff Drone",
      role: "collector",
      cost: { charge: 12, parts: 15 },
      health: { type: "constant", value: 18 },
      damage: { type: "constant", value: 2 },
      attackRate: { type: "constant", value: 0.75 },
      speed: { type: "constant", value: 60 },
      targetPriority: "weakest",
      unlock: { type: "upgradeRank", upgradeId: "drone-slip", rank: 1 },
    },
    {
      id: "barge-rig",
      name: "Barge Rig",
      role: "heavy",
      cost: { charge: 24, parts: 60, supplies: 2 },
      health: { type: "constant", value: 112 },
      damage: { type: "constant", value: 18 },
      attackRate: { type: "constant", value: 0.45 },
      speed: { type: "constant", value: 22 },
      targetPriority: "strongest",
      unlock: { type: "upgradeRank", upgradeId: "barge-yard", rank: 1 },
    },
  ],
  enemies: [
    {
      id: "dock-raider",
      name: "Dock Raider",
      health: { type: "constant", value: 24 },
      damage: { type: "constant", value: 4 },
      attackRate: { type: "constant", value: 0.8 },
      speed: { type: "constant", value: 26 },
      rewards: { parts: 4 },
      behavior: "melee",
    },
    {
      id: "reef-mutant",
      name: "Reef Mutant",
      health: { type: "constant", value: 74 },
      damage: { type: "constant", value: 10 },
      attackRate: { type: "constant", value: 0.55 },
      speed: { type: "constant", value: 20 },
      rewards: { parts: 8, supplies: 1 },
      behavior: "melee",
    },
    {
      id: "harbor-gun",
      name: "Harbor Gun",
      health: { type: "constant", value: 210 },
      damage: { type: "constant", value: 19 },
      attackRate: { type: "constant", value: 0.7 },
      speed: { type: "constant", value: 0 },
      rewards: { parts: 14, charts: 1 },
      behavior: "stationary",
    },
  ],
  zones: [
    {
      id: "pier-01-salt-market",
      name: "Pier 01: Salt Market",
      size: { width: 920, height: 680 },
      base: { x: 110, y: 340 },
      enemyClusters: [
        { enemyId: "dock-raider", count: 4, x: 540, y: 250, radius: 95 },
        { enemyId: "reef-mutant", count: 2, x: 670, y: 440, radius: 80 },
        { enemyId: "harbor-gun", count: 1, x: 790, y: 340, radius: 60 },
      ],
      unlock: { type: "always" },
      completion: { type: "allEnemiesDefeated" },
    },
    {
      id: "pier-02-crane-row",
      name: "Pier 02: Crane Row",
      size: { width: 980, height: 720 },
      base: { x: 100, y: 360 },
      enemyClusters: [
        { enemyId: "dock-raider", count: 5, x: 510, y: 210, radius: 90 },
        { enemyId: "reef-mutant", count: 3, x: 690, y: 400, radius: 90 },
        { enemyId: "harbor-gun", count: 2, x: 840, y: 300, radius: 70 },
      ],
      unlock: { type: "zoneCompleted", zoneId: "pier-01-salt-market" },
      completion: { type: "allEnemiesDefeated" },
    },
    {
      id: "pier-03-lighthouse-array",
      name: "Pier 03: Lighthouse Array",
      size: { width: 1040, height: 760 },
      base: { x: 120, y: 380 },
      enemyClusters: [
        { enemyId: "dock-raider", count: 6, x: 530, y: 220, radius: 100 },
        { enemyId: "reef-mutant", count: 4, x: 700, y: 500, radius: 100 },
        { enemyId: "harbor-gun", count: 3, x: 900, y: 350, radius: 85 },
      ],
      unlock: { type: "zoneCompleted", zoneId: "pier-02-crane-row" },
      completion: { type: "allEnemiesDefeated" },
    },
  ],
  upgrades: [
    {
      id: "shore-drills",
      name: "Shore Drills",
      description: "Harbor crews deal more damage.",
      cost: { parts: { type: "linear", base: 8, perRank: 7 } },
      effect: { type: "statMultiplier", target: "unit:harbor-crew:damage", value: { type: "additivePercent", percentPerRank: 12 } },
      maxRank: 10,
      unlock: { type: "always" },
    },
    {
      id: "patched-waders",
      name: "Patched Waders",
      description: "All crews survive longer.",
      cost: { parts: { type: "linear", base: 10, perRank: 8 } },
      effect: { type: "statMultiplier", target: "unit:*:health", value: { type: "additivePercent", percentPerRank: 10 } },
      maxRank: 10,
      unlock: { type: "always" },
    },
    {
      id: "tide-turbines",
      name: "Tide Turbines",
      description: "The harbor generates charge faster.",
      cost: { parts: { type: "linear", base: 14, perRank: 12 } },
      effect: { type: "resourcePassiveRate", resourceId: "charge", value: { type: "additivePercent", percentPerRank: 15 } },
      maxRank: 8,
      unlock: { type: "always" },
    },
    {
      id: "wreck-charters",
      name: "Wreck Charters",
      description: "Enemy wreckage yields more parts.",
      cost: { parts: { type: "linear", base: 20, perRank: 18 } },
      effect: { type: "statMultiplier", target: "reward:parts", value: { type: "additivePercent", percentPerRank: 15 } },
      maxRank: 8,
      unlock: { type: "always" },
    },
    {
      id: "supply-lockers",
      name: "Supply Lockers",
      description: "Begin each run with more supplies.",
      cost: { parts: { type: "linear", base: 12, perRank: 10 } },
      effect: { type: "resourceStartingValue", resourceId: "supplies", value: { type: "constant", value: 1 } },
      maxRank: 5,
      unlock: { type: "always" },
    },
    {
      id: "drone-slip",
      name: "Drone Slip",
      description: "Unlock Skiff Drones.",
      cost: { parts: { type: "constant", value: 30 } },
      effect: { type: "unlock", targetId: "skiff-drone" },
      maxRank: 1,
      unlock: { type: "always" },
    },
    {
      id: "barge-yard",
      name: "Barge Yard",
      description: "Unlock Barge Rigs.",
      cost: { parts: { type: "constant", value: 80 }, charts: { type: "constant", value: 2 } },
      effect: { type: "unlock", targetId: "barge-rig" },
      maxRank: 1,
      unlock: { type: "upgradeRank", upgradeId: "drone-slip", rank: 1 },
    },
  ],
};
