import type { GameConfig } from "../../config/types";

export const ashCitadelConfig: GameConfig = {
  game: {
    id: "ash-citadel",
    title: "Ash Citadel",
    version: 1,
    theme: {
      background: "#181512",
      panel: "#29211c",
      accent: "#d97706",
    },
  },
  resources: [
    {
      id: "power",
      name: "Power",
      icon: "bolt",
      startingValue: 20,
      cap: 30,
      passiveRate: { type: "constant", value: 1.5 },
      resetOnRun: true,
    },
    { id: "scrap", name: "Scrap", icon: "gear", startingValue: 0 },
    { id: "rations", name: "Rations", icon: "crate", startingValue: 5, cap: 14, resetOnRun: true },
    { id: "intel", name: "Intel", icon: "signal", startingValue: 0 },
  ],
  units: [
    {
      id: "militia-squad",
      name: "Militia Squad",
      role: "fighter",
      cost: { power: 6, rations: 1 },
      health: { type: "constant", value: 32 },
      damage: { type: "constant", value: 6 },
      attackRate: { type: "constant", value: 1 },
      speed: { type: "constant", value: 42 },
      targetPriority: "nearest",
      unlock: { type: "always" },
    },
    {
      id: "scrap-drone",
      name: "Scrap Drone",
      role: "collector",
      cost: { power: 12, scrap: 15 },
      health: { type: "constant", value: 18 },
      damage: { type: "constant", value: 2 },
      attackRate: { type: "constant", value: 0.7 },
      speed: { type: "constant", value: 58 },
      targetPriority: "weakest",
      unlock: { type: "upgradeRank", upgradeId: "drone-bay", rank: 1 },
    },
    {
      id: "siege-rig",
      name: "Siege Rig",
      role: "heavy",
      cost: { power: 24, scrap: 60, rations: 2 },
      health: { type: "constant", value: 110 },
      damage: { type: "constant", value: 18 },
      attackRate: { type: "constant", value: 0.45 },
      speed: { type: "constant", value: 22 },
      targetPriority: "strongest",
      unlock: { type: "upgradeRank", upgradeId: "rig-foundry", rank: 1 },
    },
  ],
  enemies: [
    {
      id: "raider",
      name: "Raider",
      health: { type: "constant", value: 24 },
      damage: { type: "constant", value: 4 },
      attackRate: { type: "constant", value: 0.8 },
      speed: { type: "constant", value: 26 },
      rewards: { scrap: 4 },
      behavior: "melee",
    },
    {
      id: "mutant",
      name: "Mutant",
      health: { type: "constant", value: 76 },
      damage: { type: "constant", value: 10 },
      attackRate: { type: "constant", value: 0.55 },
      speed: { type: "constant", value: 20 },
      rewards: { scrap: 8, rations: 1 },
      behavior: "melee",
    },
    {
      id: "auto-turret",
      name: "Auto Turret",
      health: { type: "constant", value: 220 },
      damage: { type: "constant", value: 20 },
      attackRate: { type: "constant", value: 0.7 },
      speed: { type: "constant", value: 0 },
      rewards: { scrap: 14, intel: 1 },
      behavior: "stationary",
    },
  ],
  zones: [
    {
      id: "block-01-broken-market",
      name: "Block 01: Broken Market",
      size: { width: 920, height: 680 },
      base: { x: 110, y: 340 },
      enemyClusters: [
        { enemyId: "raider", count: 4, x: 550, y: 260, radius: 95 },
        { enemyId: "mutant", count: 2, x: 670, y: 440, radius: 80 },
        { enemyId: "auto-turret", count: 1, x: 790, y: 340, radius: 60 },
      ],
      unlock: { type: "always" },
      completion: { type: "allEnemiesDefeated" },
    },
    {
      id: "block-02-transit-spine",
      name: "Block 02: Transit Spine",
      size: { width: 980, height: 720 },
      base: { x: 100, y: 360 },
      enemyClusters: [
        { enemyId: "raider", count: 5, x: 510, y: 210, radius: 90 },
        { enemyId: "mutant", count: 3, x: 690, y: 400, radius: 90 },
        { enemyId: "auto-turret", count: 2, x: 840, y: 300, radius: 70 },
      ],
      unlock: { type: "zoneCompleted", zoneId: "block-01-broken-market" },
      completion: { type: "allEnemiesDefeated" },
    },
    {
      id: "block-03-signal-yard",
      name: "Block 03: Signal Yard",
      size: { width: 1040, height: 760 },
      base: { x: 120, y: 380 },
      enemyClusters: [
        { enemyId: "raider", count: 6, x: 530, y: 220, radius: 100 },
        { enemyId: "mutant", count: 4, x: 700, y: 500, radius: 100 },
        { enemyId: "auto-turret", count: 3, x: 900, y: 350, radius: 85 },
      ],
      unlock: { type: "zoneCompleted", zoneId: "block-02-transit-spine" },
      completion: { type: "allEnemiesDefeated" },
    },
  ],
  upgrades: [
    {
      id: "trained-militia",
      name: "Trained Militia",
      description: "Militia squads deal more damage.",
      cost: { scrap: { type: "linear", base: 8, perRank: 7 } },
      effect: { type: "statMultiplier", target: "unit:militia-squad:damage", value: { type: "additivePercent", percentPerRank: 12 } },
      maxRank: 10,
      unlock: { type: "always" },
    },
    {
      id: "reinforced-kit",
      name: "Reinforced Kit",
      description: "All deployed crews survive longer.",
      cost: { scrap: { type: "linear", base: 10, perRank: 8 } },
      effect: { type: "statMultiplier", target: "unit:*:health", value: { type: "additivePercent", percentPerRank: 10 } },
      maxRank: 10,
      unlock: { type: "always" },
    },
    {
      id: "generator-overdrive",
      name: "Generator Overdrive",
      description: "The citadel generates power faster.",
      cost: { scrap: { type: "linear", base: 14, perRank: 12 } },
      effect: { type: "resourcePassiveRate", resourceId: "power", value: { type: "additivePercent", percentPerRank: 15 } },
      maxRank: 8,
      unlock: { type: "always" },
    },
    {
      id: "salvage-charters",
      name: "Salvage Charters",
      description: "Enemy wreckage yields more scrap.",
      cost: { scrap: { type: "linear", base: 20, perRank: 18 } },
      effect: { type: "statMultiplier", target: "reward:scrap", value: { type: "additivePercent", percentPerRank: 15 } },
      maxRank: 8,
      unlock: { type: "always" },
    },
    {
      id: "ration-vault",
      name: "Ration Vault",
      description: "Begin each run with more rations.",
      cost: { scrap: { type: "linear", base: 12, perRank: 10 } },
      effect: { type: "resourceStartingValue", resourceId: "rations", value: { type: "constant", value: 1 } },
      maxRank: 5,
      unlock: { type: "always" },
    },
    {
      id: "drone-bay",
      name: "Drone Bay",
      description: "Unlock Scrap Drones.",
      cost: { scrap: { type: "constant", value: 30 } },
      effect: { type: "unlock", targetId: "scrap-drone" },
      maxRank: 1,
      unlock: { type: "always" },
    },
    {
      id: "rig-foundry",
      name: "Rig Foundry",
      description: "Unlock Siege Rigs.",
      cost: { scrap: { type: "constant", value: 80 }, intel: { type: "constant", value: 2 } },
      effect: { type: "unlock", targetId: "siege-rig" },
      maxRank: 1,
      unlock: { type: "upgradeRank", upgradeId: "drone-bay", rank: 1 },
    },
  ],
};
